### PR TITLE
linux + recent mantl changes

### PR DESCRIPTION
**Pull request by novas0x2a**
This should make the install scripts work on linux and with a mantl install without 8080 access.

### CODE REVIEW

**Comment by hpreston** [comment]
Great thanks!  Have there been changes in the recent Mantl installs that change the Marathon API access to something other than 8080?  Or does the API already respond on port 80/443?  I've only tested with port 8080..

**Comment by novas0x2a** [comment]
Yeah, in this install, the only ports open on the control nodes are 22 and 443. I did deploy with this, and it worked, although I haven't really tested exhaustively.

**Comment by hpreston** [comment]
You caught me in the midst of some significant updates to the application.. 
- New web ui
- Default deployment stack 
- General cleanup and clarification in install process...
- probably more... 
  
  I won't be able to directly merge these fixes in.  If you have time and want to pull down the latest master and put the fixes in that would be awesome, otherwise I'll pull them in manually.  
  Thanks!

**Comment by hpreston** [comment]
I've gone ahead and manually implemented the changes you suggested into the updated code.  If you get a chance to test my updated version on your cluster that would be helpful.  I tested on OS X, Ubuntu, and CentOS, but wouldn't hurt to get a 2nd person to check it out.  

thanks again!

**Pull request closed without merging**
